name: 'Install dependencies for Unix'
description: 'Install TTK optional dependencies on Ubuntu & macOS'
runs:
  using: "composite"
  steps:

    - name: Install Spectra dependency
      shell: bash
      run: |
        wget https://github.com/yixuan/spectra/archive/v1.0.1.tar.gz
        tar xvf v1.0.1.tar.gz
        mkdir build_spectra && cd build_spectra
        cmake ../spectra-1.0.1
        sudo cmake --build . --target install --parallel

    - name: Install Torch
      shell: bash
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.1%2Bcpu.zip
        unzip libtorch-cxx11-abi-shared-with-deps-2.3.1+cpu.zip
        sudo cp -R libtorch/* /usr/local/

    - name: Install ZFP dependency
      shell: bash
      run: |
        wget https://github.com/LLNL/zfp/archive/1.0.0.tar.gz
        tar xvf 1.0.0.tar.gz
        mkdir build_zfp && cd build_zfp
        cmake \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_TESTING=OFF \
          ../zfp-1.0.0
        sudo cmake --build . --target install --parallel
